# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "stat.rain.normal", # <SPIChanges>
  "stat.rain.drought.mod", # <SPIChanges>
  "stat.rain.drought.sev", # <SPIChanges>
  "stat.rain.drought.extr", # <SPIChanges>
  NULL
))
