#' Detect trends and quantify their effect on the probability of SPI values occurring
#'
#' @param rain.at.TS
#' A 4-column matrix generated with `TSaggreg()`. No other objects are accepted.
#'  * 1st column is years (YYYY),
#'  * 2nd is the months (1 to 12),
#'  * 3rd is the quasiWeeks (1 to 4),
#'  * and 4th is the rainfall totals accumulated at a time scale.
#' @param only.linear
#' A character string value (`Yes` or `No`) defining if the function must
#' consider only linear models (`Yes`) or linear and non-linear models (`No`).
#' Default is `Yes`.
#' @returns
#' A `list` object with:
#' \describe{
#'   \item{data.week}{The Rainfall amounts, SPI, cumulative probability of the SPI values under the stationary
#'   approach, cumulative probability of the SPI values under the non-stationary approach,
#'   and the changes in the frequency of below zero SPI values caused by the changes in rainfall patterns.}
#'   \item{model.selection}{The generalized additive model that best fits the rainfall series}
#'   \item{Changes.Freq.Drought}{changes in the frequency of zero precipitation, moderate to extreme,
#'   severe to extreme and extreme drought events,as categorized by the SPI classification system,
#'   caused by the changes in rainfall patterns.
#'   Changes in the precipitation amounts associated describing normal conditions is also shown.}
#'   \item{Statistics}{Year to year changes in the expected frequency of moderate to extreme, severe to extreme
#'   and extreme drought events.}
#'   \item{data.week}{The Rainfall amounts, \acronym{SPI}, cumulative
#'   probability of the \acronym{SPI} values under the stationary approach,
#'   cumulative probability of the \acronym{SPI} values under the non-stationary
#'   approach, and the changes in the frequency of below zero \acronym{SPI}
#'   values caused by the changes in rainfall patterns.}
#'   \item{model.selection}{The generalized additive model that best fits the
#'   rainfall series}
#'   \item{Changes.Freq.Drought}{changes in the frequency of zero precipitation,
#'   moderate, severe and extreme drought events, as defined by the
#'   \acronym{SPI} classification system, caused by the changes in rainfall
#'   patterns. Changes in the precipitation amounts associated describing normal
#'   conditions is also shown.}
#'   \item{Statistics}{Year to year changes in the expected frequency of
#'   moderate, severe and extreme drought events.}
#'  }
#' @examples
#'
#' rainTS4 <- rainTS4
#' Changes_SPI <- SPIChanges(rain.at.TS=rainTS4, only.linear = "yes")
#' @importFrom dglm dglm
#' @importFrom stats Gamma binomial fitted glm pgamma predict qgamma qnorm
#' @importFrom brglm2 brglmControl brglmFit
#' @importFrom rlang arg_match
#' @importFrom brglm2 brglmFit
#' @autoglobal
#' @export
#'
#' @details
#' The `SPIChanges()` function implements a nonstationary parametric approach to detect
#' changes in precipitation patterns and assess their impact on the expected frequency
#' of Standardized Precipitation Index (SPI) values. It evaluates 16 candidate models
#' based on time-varying gamma distributions, which account for a broad range of linear
#' and nonlinear changes in both the mean and dispersion of the precipitation series.
#'
#' Model selection is performed using the second-order Akaike Information Criterion (AICc),
#' and the selected model is used to compute the cumulative probability of each
#' precipitation amount under changing climate conditions. These nonstationary probabilities
#' are then compared with those from the original, stationary SPI algorithm to identify
#' whether the frequency of drought events has increased or decreased over time.
#'
#' For detailed explanations of the gamma-based models and the model selection procedure,
#' please refer to the README and Vignettes included in the package.

SPIChanges <- function(rain.at.TS, only.linear = "Yes") {

  if (!inherits(rain.at.TS, c("TSaggreg", "matrix", "array"))) {
    stop("`rain.at.TS` must be a matrix as that generated by using `TSaggreg()`.")
  }

  if (!is.numeric(rain.at.TS) ||
      anyNA(rain.at.TS) ||
      any(rain.at.TS < 0) ||
      ncol(rain.at.TS) != 4) {
    stop("Physically impossible or missing values in `rain.at.TS`.")
  }

  n <- nrow(rain.at.TS)

  if (n < 480) {
    stop("Less than 10 years of rainfall records. We cannot proceed.")
  }

  if (n < 1440) {
    warning(
      "Less than 30 years of rainfall records. ",
      "Longer periods are highly recommended."
    )
  }

  if (any(!rain.at.TS[, 2] %in% 1:12) ||
      any(vapply(1:12, function(x) sum(rain.at.TS[, 2] == x), numeric(1)) < 32)) {
    stop("Column Month in `rain.at.TS` is probably malformed.")
  }

  if (any(!rain.at.TS[, 3] %in% 1:4) ||
      any(vapply(1:4, function(x) sum(rain.at.TS[, 3] == x), numeric(1)) < 96)) {
    stop("Column quasiWeek in `rain.at.TS` is probably malformed.")
  }

  only.linear <- match.arg(
    tolower(only.linear),
    choices = c("yes", "no")
  )

  data.week <- data.frame(
    Year = rain.at.TS[, 1],
    Month = rain.at.TS[, 2],
    quasiWeek = rain.at.TS[, 3],
    rain.at.TS = rain.at.TS[, 4],
    SPI = NA_real_,
    Exp.Acum.Prob = NA_real_,
    Actual.Acum.Prob = NA_real_,
    ChangeDryFreq = NA_character_
  )

  data.week <- data.week[
    order(data.week$Month, data.week$quasiWeek),
  ]

  model.selection <- matrix(NA_integer_, nrow = 48, ncol = 1)
  Changes.Freq.Drought <- matrix(NA_real_, nrow = 48, ncol = 7)
  Statistics <- NULL

  month <- 1
  week <- 1

  for (a in seq_len(48)) {

    rows <- which(
      data.week$Month == month &
        data.week$quasiWeek == week
    )

    rain.week <- data.week$rain.at.TS[rows]
    n.week <- length(rain.week)
    time <- seq_len(n.week)

    rain.week.nozeros <- rain.week[rain.week > 0]
    time.nonzero <- time[rain.week > 0]
    n.time.nonzero <- length(time.nonzero)

    if (n.time.nonzero < 2) {
      stop(
        "Month ", month, ", quasiWeek ", week,
        " has fewer than two positive rainfall values."
      )
    }

    probzero.st <- calc.probzero.st(rain.week)

    if (probzero.st[1] >= 0.50) {
      warning(
        "Rainfall series Month ", month, ", Week ", week,
        " has more than 50% zeros. SPI cannot assume values lower than 0."
      )
    } else if (probzero.st[1] > 0.159) {
      warning(
        "Rainfall series Month ", month, ", Week ", week,
        " has more than 15.9% zeros. SPI cannot assume values lower than -1."
      )
    } else if (probzero.st[1] > 0.067) {
      warning(
        "Rainfall series Month ", month, ", Week ", week,
        " has more than 6.7% zeros. SPI cannot assume values lower than -1.5."
      )
    }

    stationary.fit <- fit_gamma_dglm(
      rain = rain.week.nozeros,
      time = time.nonzero,
      mean.degree = 0,
      dispersion.degree = 0
    )

    stationary.pred <- predict_gamma_dglm(
      fit = stationary.fit,
      time = time
    )

    if (only.linear == "yes") {
      models <- Fit.linears(rain.week.nozeros, time.nonzero)
    } else {
      models <- Fit.Nonlinears(rain.week.nozeros, time.nonzero)
    }

    model.selection[a, 1] <- models$best
    selected.model <- models$selected.model

    selected.pred <- predict_gamma_dglm(
      fit = selected.model,
      time = time
    )

    quasiprob <- probzero.st +
      (1 - probzero.st) * gamma_cdf(
        x = rain.week,
        mu = stationary.pred$mu,
        phi = stationary.pred$phi
      )

    quasiprob <- pmin(pmax(quasiprob, 0.001351), 0.998649)
    data.week$Exp.Acum.Prob[rows] <- quasiprob

    normal.param.prob <- if (probzero.st[1] < 0.50) {
      0.50 - probzero.st[1]
    } else {
      0
    }

    mod.param.prob <- if (probzero.st[1] < 0.159) {
      0.159 - probzero.st[1]
    } else {
      0
    }

    sev.param.prob <- if (probzero.st[1] < 0.067) {
      0.067 - probzero.st[1]
    } else {
      0
    }

    ext.param.prob <- if (probzero.st[1] < 0.023) {
      0.023 - probzero.st[1]
    } else {
      0
    }

    stat.rain.normal <- gamma_quantile(
      p = normal.param.prob,
      mu = stationary.pred$mu[1],
      phi = stationary.pred$phi[1]
    )

    stat.rain.drought.mod <- gamma_quantile(
      p = mod.param.prob,
      mu = stationary.pred$mu[1],
      phi = stationary.pred$phi[1]
    )

    stat.rain.drought.sev <- gamma_quantile(
      p = sev.param.prob,
      mu = stationary.pred$mu[1],
      phi = stationary.pred$phi[1]
    )

    stat.rain.drought.extr <- gamma_quantile(
      p = ext.param.prob,
      mu = stationary.pred$mu[1],
      phi = stationary.pred$phi[1]
    )

    Model.Drought.week <- data.frame(
      Month = rep(month, n.time.nonzero),
      quasiWeek = rep(week, n.time.nonzero),
      ProbZero = NA_real_,
      mu = NA_real_,
      sigma = NA_real_
    )

    if (model.selection[a, 1] == 1) {

      quasiprob.ns <- quasiprob

      Changes.Freq.Drought[a, 1] <- round(probzero.st[1], 3)
      Changes.Freq.Drought[a, 2] <- round(probzero.st[n.week], 3)
      Changes.Freq.Drought[a, 3] <- round(stat.rain.normal, 2)
      Changes.Freq.Drought[a, 4] <- round(stat.rain.normal, 2)
      Changes.Freq.Drought[a, 5:7] <- 0

      Model.Drought.week$ProbZero <- probzero.st[time.nonzero]
      Model.Drought.week$mu <- stationary.pred$mu[time.nonzero]
      Model.Drought.week$sigma <- sqrt(
        stationary.pred$phi[time.nonzero]
      )

    } else {

      probzero <- calc.probzero(rain.week, time)
      probzero[probzero < 0.0001] <- 0

      quasiprob.ns <- probzero +
        (1 - probzero) * gamma_cdf(
          x = rain.week,
          mu = selected.pred$mu,
          phi = selected.pred$phi
        )

      nonstat.normal.param.prob <- if (probzero[n.week] < 0.50) {
        0.50 - probzero[n.week]
      } else {
        0
      }

      nonstat.normal.rain <- gamma_quantile(
        p = nonstat.normal.param.prob,
        mu = selected.pred$mu[n.week],
        phi = selected.pred$phi[n.week]
      )

      Changes.Freq.Drought[a, 1] <- round(probzero.st[1], 3)
      Changes.Freq.Drought[a, 2] <- round(probzero[n.week], 3)
      Changes.Freq.Drought[a, 3] <- round(stat.rain.normal, 2)
      Changes.Freq.Drought[a, 4] <- round(nonstat.normal.rain, 2)

      Changes.Freq.Drought[a, 5] <- round(
        if (probzero[n.week] >= 0.159) {
          100 * (probzero[n.week] - probzero[1])
        } else {
          100 * (
            probzero[n.week] +
              (1 - probzero[n.week]) * gamma_cdf(
                x = stat.rain.drought.mod,
                mu = selected.pred$mu[n.week],
                phi = selected.pred$phi[n.week]
              ) -
              0.159
          )
        },
        2
      )

      Changes.Freq.Drought[a, 6] <- round(
        if (probzero[n.week] >= 0.067) {
          100 * (probzero[n.week] - probzero[1])
        } else {
          100 * (
            probzero[n.week] +
              (1 - probzero[n.week]) * gamma_cdf(
                x = stat.rain.drought.sev,
                mu = selected.pred$mu[n.week],
                phi = selected.pred$phi[n.week]
              ) -
              0.067
          )
        },
        2
      )

      Changes.Freq.Drought[a, 7] <- round(
        if (probzero[n.week] >= 0.023) {
          100 * (probzero[n.week] - probzero[1])
        } else {
          100 * (
            probzero[n.week] +
              (1 - probzero[n.week]) * gamma_cdf(
                x = stat.rain.drought.extr,
                mu = selected.pred$mu[n.week],
                phi = selected.pred$phi[n.week]
              ) -
              0.023
          )
        },
        2
      )

      Model.Drought.week$ProbZero <- probzero[time.nonzero]
      Model.Drought.week$mu <- selected.pred$mu[time.nonzero]
      Model.Drought.week$sigma <- sqrt(
        selected.pred$phi[time.nonzero]
      )
    }

    quasiprob.ns <- pmin(pmax(quasiprob.ns, 0.001351), 0.998649)
    data.week$Actual.Acum.Prob[rows] <- quasiprob.ns

    if (a == 1) {
      Statistics <- Model.Drought.week
    } else {
      Statistics <- rbind(Statistics, Model.Drought.week)
    }

    week <- week + 1

    if (week == 5) {
      month <- month + 1
      week <- 1
    }
  }

  data.week$SPI <- stats::qnorm(data.week$Exp.Acum.Prob)

  dry.values <- data.week$SPI <= 0

  data.week$ChangeDryFreq[dry.values] <- as.character(
    100 * round(
      data.week$Actual.Acum.Prob[dry.values] -
        data.week$Exp.Acum.Prob[dry.values],
      3
    )
  )

  data.week$ChangeDryFreq[!dry.values] <- "NoDrought"

  data.week <- data.week[order(data.week$Year), ]

  data.week[, c("SPI", "Exp.Acum.Prob", "Actual.Acum.Prob")] <- round(
    data.week[, c("SPI", "Exp.Acum.Prob", "Actual.Acum.Prob")],
    3
  )

  months <- sort(rep(seq_len(12), 4))
  quasiweeks <- rep(seq_len(4), 12)

  Changes.Freq.Drought <- cbind(
    Month = months,
    quasiWeek = quasiweeks,
    Changes.Freq.Drought
  )

  colnames(Changes.Freq.Drought) <- c(
    "Month",
    "quasiWeek",
    "StatProbZero",
    "NonStatProbZero",
    "StatNormalRain",
    "NonStatNormalRain",
    "ChangeMod",
    "ChangeSev",
    "ChangeExt"
  )

  model.selection <- cbind(
    Month = months,
    quasiWeek = quasiweeks,
    model = model.selection
  )

  colnames(model.selection) <- c(
    "Month",
    "quasiWeek",
    "model"
  )

  Statistics <- round(Statistics, 3)

  list(
    data.week = data.week,
    model.selection = model.selection,
    Changes.Freq.Drought = Changes.Freq.Drought,
    Statistics = Statistics
  )
}

#' Gamma CDF using dglm
#'
#' @param x mu phi
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
gamma_cdf <- function(x, mu, phi) {
  stats::pgamma(
    q = x,
    shape = 1 / phi,
    scale = mu * phi
  )
}

#' Gamma quantile using dglm
#'
#' @param p mu phi
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
gamma_quantile <- function(p, mu, phi) {
  stats::qgamma(
    p = p,
    shape = 1 / phi,
    scale = mu * phi
  )
}

#' Scale time for numerically stable polynomial regression.
#'
#' @param time center scale
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
scale_time <- function(time, center = mean(time), scale = stats::sd(time)) {

  if (!is.finite(scale) || scale == 0) {
    scale <- 1
  }

  list(
    value = (time - center) / scale,
    center = center,
    scale = scale
  )
}

#' Create a polynomial formula for the mean or dispersion model.
#'
#' @param degree response
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
degree_formula <- function(degree, response = FALSE) {

  rhs <- switch(
    as.character(degree),
    "0" = "1",
    "1" = "time",
    "2" = "time + I(time^2)",
    "3" = "time + I(time^2) + I(time^3)",
    stop("`degree` must be 0, 1, 2, or 3.")
  )

  if (response) {
    stats::as.formula(paste("rain ~", rhs))
  } else {
    stats::as.formula(paste("~", rhs))
  }
}

#' Fit one Gamma double generalized linear model.
#'
#' @param rain time mean.degree dispersion.degree
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
fit_gamma_dglm <- function(
    rain,
    time,
    mean.degree,
    dispersion.degree
) {
  time.info <- scale_time(time)
  dat <- data.frame(
    rain = rain,
    time = time.info$value
  )
  fit <- dglm::dglm(
    formula = degree_formula(mean.degree, response = TRUE),
    dformula = degree_formula(dispersion.degree),
    family = stats::Gamma(link = "log"),
    dlink = "log",
    method = "ml",
    data = dat
  )
  fit$time.center <- time.info$center
  fit$time.scale <- time.info$scale
  fit
}

#' Predict Gamma mean and dispersion at requested time points.
#'
#' @param fit time
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
predict_gamma_dglm <- function(fit, time) {

  time.scaled <- (time - fit$time.center) / fit$time.scale

  newdata <- data.frame(
    time = time.scaled
  )

  list(
    mu = as.numeric(
      stats::predict(
        fit,
        newdata = newdata,
        type = "response"
      )
    ),

    phi = as.numeric(
      stats::predict(
        fit$dispersion.fit,
        newdata = newdata,
        type = "response"
      )
    )
  )
}

#' Validates the fitting process.
#'
#' @param fit A fitted `dglm` model object to validate.
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
valid_dglm_fit <- function(fit) {
  if (is.null(fit) || !is.finite(fit$m2loglik)) {
    return(FALSE)
  }
  mu <- stats::fitted(fit)
  phi <- stats::fitted(fit$dispersion.fit)
  if (length(mu) == 0L ||
      length(phi) == 0L ||
      any(!is.finite(mu)) ||
      any(!is.finite(phi)) ||
      any(mu <= 0) ||
      any(phi <= 0)) {
    return(FALSE)
  }
  TRUE
}

#' Fit a Gamma DGLM and discard any unstable candidate.
#'
#' @param rain time mean.degree dispersion.degree
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
fit_gamma_dglm_safely <- function(
    rain,
    time,
    mean.degree,
    dispersion.degree
) {

  warning.occurred <- FALSE

  fit <- tryCatch(
    withCallingHandlers(
      fit_gamma_dglm(
        rain = rain,
        time = time,
        mean.degree = mean.degree,
        dispersion.degree = dispersion.degree
      ),

      warning = function(w) {
        warning.occurred <<- TRUE
        invokeRestart("muffleWarning")
      }
    ),

    error = function(e) NULL
  )

  if (warning.occurred || !valid_dglm_fit(fit)) {
    return(NULL)
  }

  fit
}


#' Calculate AICc using k = 4.4 penalty.
#'
#' @param fit penalty
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
aicc_dglm <- function(fit, penalty = 4.4) {

  n <- length(stats::fitted(fit))

  df <- length(stats::coef(fit)) +
    length(stats::coef(fit$dispersion.fit))

  if (n <= df + 1 || !is.finite(fit$m2loglik)) {
    return(Inf)
  }

  fit$m2loglik +
    (penalty * df) *
    (1 + (df + 1) / (n - df - 1))
}

#' Fit and rank Gamma DGLM candidates.
#'
#' @param rain.week.nozeros time.nonzero degrees
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
fit_dglm_candidates <- function(
    rain.week.nozeros,
    time.nonzero,
    degrees
) {

  fits <- lapply(seq_len(nrow(degrees)), function(i) {
    fit_gamma_dglm_safely(
      rain = rain.week.nozeros,
      time = time.nonzero,
      mean.degree = degrees[i, 1],
      dispersion.degree = degrees[i, 2]
    )
  })

  scores <- vapply(
    fits,
    function(fit) {
      if (is.null(fit)) {
        Inf
      } else {
        aicc_dglm(fit, penalty = 4.4)
      }
    },
    numeric(1)
  )

  best <- which.min(scores)

  if (!is.finite(scores[best])) {
    stop(
      "No valid Gamma DGLM candidate could be fitted for this ",
      "month/quasiWeek rainfall series."
    )
  }

  list(
    selected.model = fits[[best]],
    best = best
  )
}

#' Fit stationary and linear Gamma DGLM candidates.
#'
#' @param rain.week.nozeros time.nonzero
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
Fit.linears <- function(rain.week.nozeros, time.nonzero) {

  degrees <- rbind(
    c(0, 0),
    c(1, 0),
    c(0, 1),
    c(1, 1)
  )

  fit_dglm_candidates(
    rain.week.nozeros = rain.week.nozeros,
    time.nonzero = time.nonzero,
    degrees = degrees
  )
}


#' Fit stationary, linear, quadratic, and cubic Gamma DGLM candidates.
#'
#' @param rain.week.nozeros time.nonzero
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
Fit.Nonlinears <- function(rain.week.nozeros, time.nonzero) {
  degrees <- rbind(
    c(0, 0),
    c(1, 0),
    c(0, 1),
    c(1, 1),
    c(2, 0),
    c(0, 2),
    c(2, 1),
    c(1, 2),
    c(2, 2),
    c(3, 0),
    c(0, 3),
    c(3, 1),
    c(1, 3),
    c(3, 2),
    c(2, 3),
    c(3, 3)
  )

  fit_dglm_candidates(
    rain.week.nozeros = rain.week.nozeros,
    time.nonzero = time.nonzero,
    degrees = degrees
  )
}

#' Calculate nonstationary probability of zero rainfall.
#'
#' @param rain.week time
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
calc.probzero <- function(rain.week, time) {
  zero.rain <- as.integer(rain.week == 0)
  if (length(unique(zero.rain)) < 2L) {
    return(calc.probzero.st(rain.week))
  }
  time.scaled <- as.numeric(scale(time))
  model <- stats::glm(
    zero.rain ~ time.scaled,
    family = stats::binomial(link = "logit"),
    method = brglm2::brglmFit,
    control = brglm2::brglmControl(
      maxit = 500,
      slowit = 0.5,
      max_step_factor = 50,
      type = "AS_mean"
    )
  )
  if (!isTRUE(model$converged)) {
    warning(
      "The nonstationary zero-rainfall model did not converge; ",
      "using the stationary zero-rainfall probability instead."
    )
    return(calc.probzero.st(rain.week))
  }
  stats::fitted(model)
}

#' Calculate stationary probability of zero rainfall.
#'
#' @param rain.week Numeric vector of rainfall amounts for one month/quasi-week.
#' @author Adam H. Sparks \email{adamhsparks@@gmail.com}
#' @author Gabriel C. Blain \email{gabrielblain@@gmail.com}
#' @noRd
#' @keywords Internal
calc.probzero.st <- function(rain.week) {
  n.rain <- length(rain.week)
  n.z <- sum(rain.week == 0)
  prob.zero.rain <- n.z / (n.rain + 1)
  rep(prob.zero.rain, n.rain)
}
